name: ditto
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=2.0.1
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=12.1
  - mkl=2023.1.0
  - mkl-service
  - mkl_fft
  - mkl_random
  - pillow=11.0.0
  - jinja2
  - tqdm
  - requests
  - filelock
  - certifi
  - scipy
  - scikit-learn
  - scikit-image
  - openssl
  - xz
  - zlib
  - yaml
  - lz4-c
  - tk
  - typing_extensions
  - freetype
  - ffmpeg
  - zstd
  - intel-openmp
  - tbb
  - networkx
  - pyyaml
  - sqlite
  - sympy
  - setuptools
  - pip:
      - audioread==3.0.1
      - cffi==1.17.1
      - cuda-python==12.6.2.post1
      - cython==3.0.11
      - decorator==5.1.1
      - filetype==1.2.0
      - imageio==2.36.1
      - imageio-ffmpeg==0.5.1
      - joblib==1.4.2
      - librosa==0.10.2.post1
      - numba==0.60.0
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.6.0.74
      - opencv-python-headless==4.10.0.84
      - platformdirs==4.3.6
      - pooch==1.8.2
      - soundfile==0.13.0
      - soxr==0.5.0.post1
      - threadpoolctl==3.5.0
      - tifffile==2024.12.12
      - tqdm==4.67.1
      - polygraphy
      - colored
      - triton-3.1.0-cp310-cp310-win_amd64.whl
